version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      TZ: America/Guayaquil
    ports:
      - '9200:9200'
    restart: on-failure
    volumes:
      - ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    environment:
      TZ: America/Guayaquil
    ports:
      - '5601:5601'
    restart: on-failure
    volumes:
      - ./configs/kibana.yml:/usr/share/kibana/config/kibana.yml

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.0
    environment:
      TZ: America/Guayaquil
    ports:
      - '5050:5050'
    restart: on-failure
    volumes:
      - ./configs/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf

volumes:
  elasticsearch_data:

networks:
  default:
    external: true
    name: elk-sandbox_network
